# Stage 2 synthesis generator (fork, 2026-07-21): builds dedup_merge_map_v0_1.json +
# canonical_rules_draft_v0_1.json from the frozen miner outputs with full-coverage
# verification (every raw entry in exactly one merge group). Group spec is human-authored.
import json
import os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "raw_miner_outputs")
FILES = {"1": "miner1_july_live_sessions_a.json", "2": "miner2_july_live_sessions_b.json",
         "3": "miner3_older_and_short_recordings.json"}
raw = {k: json.load(open(os.path.join(RAW, v), encoding="utf-8")) for k, v in FILES.items()}

G = [
("setup", "Unmitigated levels (untested OBs, FVGs, BPRs, session highs/lows) act as magnets: price is expected to return to mitigate them; they are marked, kept on the chart, and used as entry/target references.", "2:11 2:67 3:15",
 "Across the next 5 zone campaigns, entry zones and TP levels coincide (>=4/5) with levels bar data shows untouched since formation.",
 "Campaign zones repeatedly placed at levels bar data shows already traded through, while nearby untouched levels are ignored."),
("setup", "OB lifecycle: an OB is created by an impulsive displacement move that leaves an FVG; a fresh (never-tested) OB is strong, an OB retested a couple of times is weak, is expected to fail, and is not re-entered.", "1:19 2:83 3:19 2:92 2:93 1:39",
 "Campaign entry zones sit at first-touch (fresh) OBs in >=4 of the next 5 zone campaigns (bar-verifiable).",
 "Campaign entries repeatedly placed at OBs already tested 2+ times since formation."),
("setup", "FVG-claim cascade: once price candle-closes through the first opposing FVG on the 5/15-minute, expect the remaining opposing FVGs to be claimed and price to run to the origin extreme ('the highest level that made the lowest level', or inverse).", "1:13 1:25 1:45 2:16 2:79 3:37",
 "In bar data around future campaigns, narrated first-FVG-claim events are followed by traversal to the identified origin level in the majority of instances.",
 "Repeated first-claim events where price reverses before the origin level without him flagging invalidation."),
("setup", "BPR (balanced price range - overlapping opposing FVGs) is a mitigation-owed rejection zone traded on its first retest; claimed to 'always work on gold' on the 15-minute (5-minute version conditional on structure).", "1:8 2:77 2:78",
 "Future campaign zones repeatedly coincide with bar-identifiable BPRs and first retests reject in the stated direction.",
 "Multiple first-retests of identified BPRs traverse without rejection during live campaigns."),
("setup", "Broken levels flip roles (broken resistance/OB becomes support and vice versa) and old levels - even months old - remain valid references when extended right.", "1:9 1:47 1:50",
 "Future campaign zones/TPs repeatedly land on role-flipped or historical levels identifiable in bar data.",
 "Campaigns consistently ignore role-flipped levels that price then respects, or use them and price ignores them."),
("setup", "Trade only at high-probability zones built from roughly 4-7 stacked confluences (structure break, ORB, gaps, liquidity, POC, VWAP, FVG, OB, equal lows); stacked liquidity locates where price can reverse; weekly-resistance+multi-OB stacks are worth at least ~100 pips of rejection.", "3:5 1:15 2:72 2:73 3:81 1:62",
 "Published campaign zones consistently coincide with >=3 independently identifiable confluence features in frozen bar data.",
 "Campaigns repeatedly posted at levels where at most one such feature is identifiable."),
("setup", "Cluster doctrine: clusters are broad battle areas (vs institutional/precise OBs); 'which cluster made that high/low?' locates the return zone; his personal structure break requires TWO clusters broken with 1-minute candle closes.", "3:10 3:79 3:80",
 "His narrated level choices repeatedly reference the cluster that made the extreme, verifiable as prior consolidation areas in 1m bars.",
 "Narrated analyses repeatedly place return zones unrelated to any identifiable origin cluster."),
("setup", "Sweep-then-reverse: after a liquidity sweep of a session high/low expect reversal (short a swept high, long the retest after a swept low); a sweep is only confirmed by the subsequent break of structure + retest + continuation.", "1:14 3:17 3:34 3:62",
 "Future campaigns repeatedly enter after bar-verifiable sweeps of session extremes followed by his stated confirmation sequence (F007's own rationale already cites a low sweep).",
 "Campaigns repeatedly entered at swept levels with no confirmation sequence, or sweeps consistently continue rather than reverse in his narrated instances."),
("setup", "Wick reading: clustered downside wicks = buyers (upside = sellers); 3-4 equal wicks are engineered liquidity that price will run; a large opposing wick with the body closing near the extreme marks the strong side.", "1:24 3:54 2:85 1:59",
 "Narrated bias calls repeatedly match bar-verifiable wick clusters, and equal-wick zones get run within the session in cited instances.",
 "Cited wick-cluster reads repeatedly resolve opposite to the stated side."),
("setup", "Flat-top/flat-bottom candles (heavy-volume signature) are unmitigated levels gold must revisit; reversals are wicks, flat candles get mitigated.", "3:53",
 "Bar data around future campaigns shows flat-extreme candles revisited before continuation in the majority of narrated cases.",
 "Repeated narrated flat-candle levels never revisited while price trends away."),
("setup", "Futures (CME/MGC) gaps act as magnets on gold: gaps get filled, and absence of remaining gaps above removes the reason to go up.", "3:51",
 "His direction calls repeatedly cite gap state and price fills cited gaps within the narrated horizon.",
 "Cited unfilled gaps repeatedly ignored by price over his stated horizons."),
("setup", "ORB doctrine: the opening range is the first 15 minutes of London (9:00-9:15) and New York (15:30-15:45 GMT+1); do nothing inside it; the breakout-then-retest with confluence is the recurring (2-3x/week) setup; the midline is hidden liquidity and never-retested ORB levels get revisited; sometimes the right London action is waiting for the ORB retest.", "3:43 3:44 3:45 3:46 3:47 3:48",
 "Future campaigns/scalps cluster at ORB breakout-retest points computable from bars once the 15-minute window is audio-confirmed.",
 "Campaign timing shows no relationship to ORB windows across many instances, or the audio check shows a different window than 15 minutes."),
("setup", "Pivot-level system: after a break of structure, box the move from wick high to wick low; the box midpoint is a pivot owed a retest, and unmitigated pivots are targets/entry zones.", "3:50",
 "Narrated/posted levels repeatedly coincide with BOS-box midpoints computable from bars (wick semantics audio-confirmed).",
 "Computed pivots show no better-than-chance coincidence with his levels."),
("setup", "Fake-move recognition: low/no-volume grinds ('staircase up, elevator down'), one-shot straight dumps without the sideways-clear-cluster rhythm, and no-volume moves on the fixed-range profile are market-maker traps - stand aside.", "3:55 1:73 3:32",
 "His no-trade calls repeatedly coincide with bar-verifiable low-body-volume grinds that subsequently reverse.",
 "Cited trap patterns repeatedly continue trend rather than reversing."),
("setup", "Low-TF reversal traps: a grind leaving FVGs that then prints CHoCH + first-FVG claim yields one large impulsive reversal candle ('hallelujah candle'); Asia-low break WITHOUT a lower low plus CHoCH and 5m-OB reclaim is a bear trap.", "1:71 1:72",
 "Narrated reversal calls repeatedly follow the stated CHoCH+first-claim sequence in bars.",
 "The stated sequence repeatedly fails to produce the impulsive reversal in his cited examples."),
("setup", "An inverted FVG (a claimed FVG) acts as resistance/support, especially when never retested.", "1:69 3:92",
 "Future campaign zones/TPs repeatedly land at bar-identifiable IFVGs.",
 "Identified IFVGs repeatedly traversed without reaction at his cited levels."),
("setup", "The market ranges ~90% of the time and the longer the range the bigger the eventual move; scalps are taken inside ranges rather than waiting out every breakout.", "1:49 3:75",
 "His trade cadence continues to show intra-range scalps between zone campaigns.",
 "He trades breakouts exclusively or abstains from all in-range activity while teaching the opposite."),
("setup", "A trendline/level tested many times will eventually break - count the touches and expect the break.", "3:56",
 "Narrated multi-touch levels break within his stated horizon in cited instances.",
 "Cited 5+-touch levels repeatedly hold indefinitely."),
("setup", "News is used by the market to reach levels faster; the pre-marked levels, not the news direction, define the trade.", "2:24",
 "During news events his posted trades continue to anchor to pre-marked levels (zones posted before the news timestamp).",
 "Campaigns posted during news that chase the news direction without any pre-marked level."),
("setup", "Round numbers (e.g. 4,300) are treated as psychological support where 'everybody will take a long'.", "3:83", "", ""),
("setup", "Gold respects levels/gaps/flat candles better than crypto - the stated reason the system is applied primarily to gold.", "3:88", "", ""),
("setup", "Trend identification heuristic (attributed to mentor Carl): is price heading to the top-right or bottom-right of the screen.", "3:77", "", ""),
("setup", "PO3 framing (accumulation, manipulation, expansion) endorsed as entry framing at high-timeframe OBs.", "2:63", "", ""),
("entry", "Core A+ entry: a session high/low (especially Asia) broken with candle-close confirmation, then a retest of the OB/FVG that made the break, then continuation entry (multi-point) toward the origin extreme / next liquidity - the setup family the group's statistics are quoted for.", "1:2 1:52 1:80 1:84 2:17 2:57 2:66",
 "Of the next 5 zone campaigns, >=4 are preceded by a same-direction session-level break with candle close, with the zone at the break's origin structure (bar-verifiable; F007's rationale already fits).",
 "Multiple campaigns whose zones have no preceding session-level break or sit unrelated to any break-origin structure."),
("entry", "Break confirmation is a close-stack: 5-minute, 15-minute and 1-hour candle closes beyond the level (two-three 5m closes suffice for scalps).", "1:4 1:53 2:3 3:13",
 "Campaign entries repeatedly follow bar-verifiable multi-timeframe closes beyond the referenced level before the post timestamp (timeframes audio-confirmed first).",
 "Entries repeatedly posted before any close beyond the level, or the audio check contradicts the 5/15/60 stack."),
("entry", "Confirmation ranking: change of character is the strongest confirmation (best on the 15-minute; low-TF after session breaks), then the engulfing candle (final check), then low-TF FVG creation with a candle close.", "1:7 1:64 1:66 3:36",
 "His narrated entries repeatedly cite CHoCH first (F007's rationale cites 1/3m CHoCH), verifiable once CHoCH is deterministically defined.",
 "Narrated entries repeatedly proceed with no CHoCH while one was available, or rank engulfing above CHoCH in practice."),
("entry", "A break is valid only with a candle close beyond the level: a wick-only excursion is a sweep, and a BOS without a close is weak and expected to fail (applies from 5-minute to weekly).", "3:11 3:12 2:84 2:54",
 "His continuation/reversal calls consistently condition on closes vs wicks in bar-verifiable instances.",
 "Narrated valid breaks repeatedly lack closes, or wick-only breaks are treated as continuation."),
("entry", "OB-claim gating: no continuation/longs until price candle-closes above the overhead OB (daily/1h/zone) and retests it; until then expect ranging below it.", "2:14 2:15 2:39 3:20 2:25",
 "Long campaigns repeatedly posted only after bar-verifiable closes above cited overhead OBs.",
 "Long campaigns repeatedly posted directly below unbroken overhead OBs he has marked."),
("entry", "The pullback entry is the origin structure of the move - the OB at the break of structure (often with flat candle + gap), never a percentage retracement; best form: candle close above the daily FVG then pullback into the OB.", "1:46 2:56 3:82 2:91",
 "Campaign zones repeatedly reconstruct as BOS-origin OBs rather than fib levels (bar-verifiable).",
 "Zones repeatedly sit at percentage retracements with no identifiable origin structure."),
("entry", "Entries are multi-point ladders (3/4/5 fills, e.g. five 0.2 lots of one total lot) across a zone built from overlapping 5m/15m/1h OBs, all sharing one stop; never add outside the range.", "1:18 1:48 2:5 3:22",
 "Future campaigns keep publishing zone ranges (not single prices) with multi-fill management instructions (already observed F006/F007).",
 "Campaigns revert to single-price entries with adds outside the published range."),
("entry", "Reaction-first entries: at a target zone wait for the rejection/reaction (or BOS + retest) before entering; no blind limit orders at reaction zones; with size, wait for the retest for better price.", "2:41 2:42 3:91 1:40",
 "His entries continue to postdate zone-touch by a reaction interval rather than resting at the level (timestamp-verifiable).",
 "Entries repeatedly fill at first touch with limit-order language for reaction zones."),
("entry", "Triple confirmation for longs: opposing FVG claimed with a close + new bullish FVG and CHoCH created + candle close above Asia high.", "2:80",
 "Long campaigns repeatedly follow all three bar-verifiable conditions.",
 "Longs repeatedly posted with none of the three conditions present."),
("entry", "Market-maker presence check: fresh FVGs/OBs being created with closes in your direction plus more liquidity resting beyond on the HTF; sideways price creating no FVGs means the maker is absent.", "1:16 1:65",
 "Narrated go/no-go calls track bar-verifiable FVG-creation density.",
 "Cited no-FVG sideways phases repeatedly continue trending without reversal."),
("entry", "Internal-structure scalping: sub-5-minute internal breaks (1m break confirmed on 3/5m, retest of a small 1m OB) for scalps especially in Asia/inside ranges; external+internal broken together = high probability.", "2:65 2:28 3:35 1:33",
 "His Asia/range scalps reconstruct as internal-structure plays on 1m bars in cited instances.",
 "Internal-break scalps repeatedly cited but bar data shows entries unrelated to internal structure."),
("entry", "Gap-short setup: price reaches a gap, candle-closes below it, the retest fails to reclaim - short.", "3:52",
 "Narrated gap-shorts follow the close-below-then-failed-retest sequence in bars.",
 "Cited gap-shorts entered without closes or with reclaimed retests."),
("entry", "Volume-comparison entry: when one breakout carries visibly more volume than a prior one, its origin zone is the one to buy on retest, with a bigger stop for the bigger move.", "1:74",
 "Narrated zone choices repeatedly prefer the higher-volume breakout origin (candle-body verifiable).",
 "Zone choices show no relation to relative breakout volume in cited instances."),
("entry", "Fishel crypto scalp system: four synced timeframes (1h direction, entries on 1m, monitored 1m+5m); 50 EMA bias, 5/13 EMA continuation (lost = back to 50), 200/800 EMA S/R; entries need 2-3 timeframes claiming the 50 EMA + vector-candle volume + stochastic reset.", "3:64 3:65 3:66", "", ""),
("timeframe", "High timeframe is king: HTF direction and confluence override low-TF signals; mapping is strictly top-down (weekly/3-day/daily/12h/4h down to 5m/1m execution) and HTF confluence is mandatory, not optional.", "3:8 1:22 2:60 2:12",
 "Campaign directions continue to align with HTF structure state at post time (bar-verifiable).",
 "Campaigns repeatedly posted against the daily/4h direction he simultaneously marks."),
("timeframe", "Level strength scales with timeframe: daily > 12h > 4h > 1h > 15m > 5m OBs; the 3-day and 12h levels are especially respected on gold.", "1:17 2:69 2:26",
 "His zone selections repeatedly prefer the higher-TF structure when levels conflict.",
 "Zone selections repeatedly prefer low-TF levels over available HTF ones."),
("timeframe", "Working set: 4-5 charts (12h/daily/weekly/4h for bias) with execution on the low timeframe (1-minute, sometimes 15-30 seconds).", "3:9",
 "Screen-share/panel evidence continues to show the multi-chart layout with 1m execution.",
 "Evidence of single-chart or high-TF-only execution."),
("session", "Monday/Asia avoidance: no Monday-Asia trades (weekend gap risk); he skips Asia roughly 9 times out of 10 (and when traded, only toward marked higher levels, and not when Asia falls in his nighttime); Monday entries come late (end of London or US).", "1:27 3:1 3:2 2:59",
 "Campaign post timestamps continue to avoid Monday Asia hours (F006/F007 both posted after 08:00Z).",
 "A cluster of campaigns posted during Monday Asia hours."),
("session", "Friday discipline: at most one trade, sometimes none or very early; Monday and Friday are the riskiest days.", "1:28 2:4",
 "Fridays continue to show 0-1 campaigns, skewed early (supports H-FPL-07's Friday-close filter).",
 "Multiple multi-campaign Fridays with late entries."),
("session", "Weekend/holiday regime: CME-closed weekend price action is not respected; positions are closed before the weekend (fees + gap risk); holiday/low-volume periods mean small choppy ranges - scalp only.", "1:26 1:85 3:73 3:74",
 "No campaign is left open into a weekend (terminal instructions or closes before Fri 21:00Z - matches F00x history).",
 "A campaign deliberately held through a weekend without stated exception."),
("session", "When London breaks Asia high, expect the US session to continue in the same direction.", "2:75",
 "Bar-verifiable London-break days continue into US in the same direction in the majority of narrated instances.",
 "Cited London-break days repeatedly reverse in US without his flagging exceptions."),
("session", "The US session first grabs liquidity from both sides before committing to one direction - don't be shaken out by the initial two-sided sweep.", "2:76",
 "US opens around his campaigns repeatedly show two-sided sweeps before the directional move (bar-verifiable).",
 "US opens repeatedly one-directional from the bell in cited instances."),
("session", "Volume gates trading: session opens (London/US, first ~1-1.5h) provide the direction; no-volume periods and market-about-to-close windows are no-trade.", "2:43 1:43",
 "Campaign timing continues to cluster inside session-open volume windows and avoid the last pre-close hour.",
 "Campaigns repeatedly posted in dead-volume or pre-close windows."),
("session", "Avoid pre-market (end of London into the US open): London profit-taking plus pre-US news make it difficult and manipulated.", "3:42",
 "Campaign timestamps avoid the late-London-to-US-open band (checkable across future campaigns).",
 "Campaigns cluster in exactly that band."),
("session", "He does not (yet) trade the Asia ORB; ORB settings are active for London/US only.", "3:49", "", ""),
("stop", "After TP1 (or roughly 50-60+ pips in profit), the stop moves to entry making the trade risk-free; members are expected to do it unprompted.", "3:24 1:36 1:82 2:8 3:89",
 "Future campaigns continue to issue SL-to-entry after first partials (observed in F004/F006/F007).",
 "Campaigns repeatedly run to TP2+ with the stop left at origin and no BE instruction."),
("stop", "Wider stops when unmitigated levels/liquidity sit beyond the entry (an adverse sweep is expected first); shared/group trades use deliberately bigger stops beyond session extremes because followers are not at the chart.", "2:9 2:71 3:28",
 "Published stops repeatedly sit beyond identifiable unmitigated levels/session extremes rather than at fixed distances.",
 "Published stops repeatedly sit inside obvious unswept liquidity that then takes them out."),
("stop", "Stops are structural ('easy invalidation'): a little beyond the tested wick/swing/FVG whose break invalidates the idea; a second return to the entry level means the idea is dead.", "1:54 2:87 3:29 1:37",
 "Published stops reconstruct as structural invalidation points in bar data across future campaigns.",
 "Stops repeatedly placed at round distances with no structural referent."),
("stop", "Crypto uses somewhat bigger stops due to volatility.", "1:81", "", ""),
("stop", "Stated stop/target parameter instance: ~50-pip stop against 100-500-pip targets at stacked levels.", "3:27", "", ""),
("target", "Take-profit levels sit at unmitigated old OBs/FVGs - price bounces at levels never mitigated.", "1:10",
 "Published TP levels repeatedly coincide with bar-identifiable unmitigated structures (checkable per campaign).",
 "TPs repeatedly at arbitrary distances unrelated to any unmitigated level."),
("target", "Aggressive scaling out: partial profits early and often (fixed fractions; 50-90% off after impulsive moves; bank ~every 50 pips; exit fast in ranges) because gold reverses fast - 'take profit is how I became profitable'.", "3:23 3:25 2:18 2:23 2:29 2:89 1:67",
 "Campaign management continues the TP1/partial/percent-off pattern (observed F004-F007).",
 "Campaigns switch to single-exit all-or-nothing management."),
("target", "Daily target frame: ~100-300 pips per day taken as sub-5m scalps (a small piece of the move), then done for the day; single-TP 200-300 when all session liquidity rests one side at an HTF OB.", "1:6 1:68 2:36 3:26",
 "Published TP ladders continue to sum to roughly this order of magnitude per campaign.",
 "TP ladders repeatedly target multiples beyond this frame or he holds for full swings."),
("target", "Even a valid mitigation produces at least a 100-200 pip bounce ('dead cat') - enough for the scalp long.", "3:84",
 "Bar data at future mitigated levels shows >=100-pip bounces in the majority of cited instances.",
 "Cited mitigations repeatedly bounce under 100 pips."),
("management", "Return-to-entry protocol: when price comes back to the averaged entry after partial fills, close the worst entry (in profit/breakeven), hold the best, move stop to entry and take partials.", "3:21 2:7",
 "Future campaigns repeat the close-worst/hold-best instruction family (observed F006 45938, F007 45973); WHICH leg is held must be audio-confirmed (one transcript self-contradicts).",
 "A campaign instruction resolves the ambiguity the other way (hold worst), or audio shows the doctrine differs from the wire's CLOSE_WORST/HOLD_BEST semantics."),
("management", "Hold a winner until the market makes another higher high (or exit into market close).", "2:35",
 "Runner-management instructions continue to reference the next higher high / market close.",
 "Runners repeatedly closed mid-structure with no reference to either."),
("management", "Duration policy: same-day closes; usually under an hour in a trade (personal scalps 5-10 minutes); no overnight/swing holds on gold (BTC exception: 1-2 days when fully confirmed); range entries exist partly to avoid 6-7-hour sits.", "1:20 1:77 2:48 3:69 2:6",
 "Campaign lifecycles continue to resolve same-day (F004-F007 all did).",
 "A gold campaign deliberately held overnight without stated exception."),
("management", "Invalidation-cut: when price reclaims the 5m FVG + OB against the position, cut immediately (do not wait for the stop) and consider reversing toward the origin.", "1:70",
 "A future losing campaign shows an early discretionary exit instruction at the reclaim point rather than a stop-out.",
 "Positions repeatedly held to full stop through obvious reclaims he has taught as invalidation."),
("management", "After a stop-out: look for a recovery re-entry on the corrected read, but never force a setup - wait for the next valid one (both halves stated; reconciled as 'recover, don't force').", "1:56 3:72",
 "Post-stop behaviour shows re-entries only at newly valid setups.",
 "Immediate revenge re-entries with no new setup, or a blanket no-re-entry policy stated."),
("management", "React-don't-predict doctrine: wait for the market to show its hand, play the probabilities with a checklist, trade level-to-level, and execute the plan mechanically regardless of single outcomes.", "1:41 1:78 1:61 2:40 2:102 2:30 2:46",
 "Campaigns continue to be reactive (posted after condition confirmation, per timestamps) rather than predictive limit placements.",
 "Campaigns shift to forecast-style pre-placed targets without condition language."),
("management", "Review/journaling discipline: journal every trade, review losses honestly, ~2h weekend chart review; keep one system for years adjusting only slightly; ~30 min/day learning cadence.", "3:30 2:101 3:106 3:107",
 "Continued references to journal counts and weekend reviews in future sessions.", ""),
("management", "Alarm-driven workflow: mark levels, set alarms (indicator 'Asia trap' etc. on the 5-minute), leave the chart; on alarm check the closes, the origin OB and whether it is news time, then wait for the retest and act; set-and-forget multi-trade placement beats screen-sitting.", "1:12 1:63 2:34 2:88 3:39",
 "Future sessions continue to show alarm-triggered analysis rather than continuous watching.", ""),
("management", "If the entry level is lost, expect the next stacked zone below (session liquidity + FVG + BPR + fresh OB) and look for the re-entry there.", "3:18",
 "Failed zones are followed by re-entry campaigns at the next stacked zone (observed F006 pattern).",
 "Failed zones repeatedly abandoned with no lower-zone re-entry when one exists."),
("filter", "Two-zones-only: at most one buy and one sell zone per day; between them do nothing - skip the day if price never reaches a zone; a missed trade means waiting for the next zone, never chasing; no mid-range/midpoint trades however convincing the shape.", "1:21 3:4 2:45 2:94 2:82",
 "Campaign frequency stays at 0-2/day anchored to pre-stated zones (observed cadence to date).",
 "Multiple same-day campaigns at unplanned mid-range prices."),
("filter", "Session-break state gates direction: Asia low lost with a close = shorts only; Asia high broken = no sells (rare high-confluence exceptions; longs preferred); Asia high NOT broken = the A+ long is off (small counter-scalps at most).", "2:2 2:74 2:90 1:51",
 "Campaign directions continue to match the session-break state at post time (bar-verifiable; F007 LONG followed an Asia-high context per his rationale).",
 "A campaign posted counter to its session-break state without stated exception."),
("filter", "News filters: FOMC days take few trades; stacked-news days are 'search and destroy' whipsaws - rely on marked levels; no trading during major political speeches; less news-following = better trading.", "3:40 3:41 2:47",
 "No-campaign gaps continue to coincide with major-news windows (calendar-checkable).",
 "Normal campaign cadence straight through FOMC-class events, repeatedly."),
("filter", "'No room' filter: a break with resistance directly overhead has no reward - skip the continuation, prefer the other side or wait.", "3:16",
 "Skipped-break narrations continue to cite overhead structure (F006 pre-entry commentary already did).",
 "Campaigns repeatedly launched into overhead structure he has marked."),
("filter", "FVG-void filter: before selling a breakdown, check the prior up-move for downside FVGs - none means price goes up first (stop-hunt) before continuing down.", "3:31",
 "Future sell decisions reference downside-FVG presence; bar data confirms the up-first path when absent, in narrated cases.",
 "Cited no-FVG breakdowns repeatedly continue straight down."),
("filter", "Both-sides-swept day: when Asia high AND low both break in the same day, read the second break as a sweep/confirmation, not continuation.", "3:33",
 "Both-sides days in bar data resolve as reversals of the second break in the majority of narrated instances.",
 "Second breaks on both-sides days repeatedly continue trending."),
("filter", "Do not trade inside high-timeframe FVGs - use the low-timeframe OBs within them for execution.", "2:13",
 "Entry zones repeatedly reconstruct as low-TF OBs even when sitting inside HTF FVGs.",
 "Zones repeatedly span whole HTF FVGs with no low-TF structure."),
("filter", "Trend-side only: in an uptrend take retest longs only (never counter-shorts, never long the top); do not buy at range high - look for the sell there.", "1:44 3:7 3:38",
 "Campaign directions continue to align with the marked trend state; no counter-trend entries without stated exception.",
 "Repeated counter-trend campaigns against his own marked structure."),
("filter", "Do not buy directly under a big 1-hour rejection wick - the sellers are active there; the buy belongs at the stacked zone below.", "2:86",
 "Buy zones continue to sit below (not at) large 1h rejection wicks in bar data.",
 "Buy zones repeatedly placed immediately under fresh 1h rejection wicks."),
("filter", "Focus: one instrument (gold - the system's statistics are gold-built), at most two; BTC only for A+++ setups; silver and oil are not traded.", "1:57 2:21 2:61 3:87 2:51 1:32",
 "The gold-trades channel remains ~100% XAUUSD campaigns (author-scope evidence already shows this); BTC posts stay rare/high-grade.",
 "Regular multi-instrument campaigns in the gold lane."),
("filter", "Crypto correlation: when BTC goes down everything in crypto goes down; altcoin trades are conditional on the BTC picture (gold does not behave this way).", "2:62", "", ""),
("risk", "Loss-first risk framing: decide the loss before entry and mentally spend it; equal risk per trade at 1:2-1:3 reward:risk; ~5 trades/week stays profitable even losing two; never all-in regardless of win rate.", "2:19 2:20 3:70",
 "Stated risk framing recurs; published stop distances vs TP ladders continue to imply roughly 1:2-1:3.",
 "Published campaigns repeatedly imply sub-1:1 structures or all-in language."),
("risk", "Sizing ladder: roughly a 10-25K account for one lot; below that 0.1/0.01 and build gradually (thresholds drift between sessions; one negation garbled).", "1:34 1:75",
 "The audio check confirms the thresholds and future sizing advice repeats them.",
 "Audio shows materially different thresholds, or later sessions contradict the ladder."),
("risk", "Confluence-scaled risk: risk more on A+/high-probability zones (wallet and psychology permitting); few meaningful trades beat many small ones; increase size only after a confirmed break of structure.", "1:35 1:76 3:90 2:97 2:31",
 "'Bigger size' remarks continue to attach to A+/BOS-confirmed campaigns (observed 2026-07-02 instance).",
 "Size-up remarks attach to low-confluence trades, repeatedly."),
("risk", "Month-end: keep risk low because the market 'does stupid stuff'.", "2:70",
 "Reduced-size/no-trade language recurs at month-ends.",
 "Month-end sessions repeatedly show size-up behaviour."),
("risk", "Performance is judged at month-end, not per trade: several stop-losses per month are acceptable if the month ends green.", "3:71",
 "The framing recurs after future losses.", ""),
("risk", "Daily percent discipline: ~1-3% per day; once hit, protect or stop trading; never round-trip a winner (BE at ~0.2% up on scalps).", "3:67",
 "Done-for-the-day language continues to follow target-sized wins.",
 "Continued trading after stated daily targets, repeatedly."),
("risk", "His stated personal gold scalp parameters: 1-4 candles per trade, 0.03-0.2 lots, ~$200 per scalp, up to three times a day.", "3:68", "", ""),
("risk", "Risk less on altcoins (Solana) than on gold/BTC - it is still crypto.", "2:22", "", ""),
("indicator", "Playbook indicator usage doctrine (PRIOR ART FP-INDICATOR-005/006 - transcript evidence only, not a discovery): a levels-not-signals tool (session H/L, FVG/BPR/OB/CHoCH/IFVG/engulfing, high-probability-OB filter, green/red panel checklist, 'old Asia sessions', 'all OBs', alert routes); the engulfing overlay is toggled on only at execution; keep the chart clean.", "1:0 1:1 1:86 2:32 2:33 2:96 3:109 2:95",
 "Panel/feature references in future sessions stay consistent with the documented catalogue (FP-INDICATOR-005/006).",
 "Panel semantics change materially (indicator-version drift risk, already registered)."),
("indicator", "VWAP: above = bullish, below = bearish (institutional fair price); losing daily+weekly+monthly VWAP means every push up is a short; a flat/sideways VWAP means no volume - stand aside.", "3:59",
 "VWAP-state references recur in gold session analyses and match bar-computable VWAP states.",
 "His bias calls repeatedly contradict the VWAP rules he teaches."),
("indicator", "Volume-profile rules: fixed-range VAH = sell, VAL = buy, POC = intermediate target/support; below the daily value area = bearish (retest short) until reclaimed; claiming the weekly POC allows longs to the next weekly POC.", "3:57 3:58",
 "VP-level references recur and match computable fixed-range profiles in cited instances.",
 "Cited VP levels repeatedly ignored by his own trade choices."),
("indicator", "Session-box rules: lose the box level then fake-retest = short; hold the level and break out = long; volume ('yellow') candles mark market-maker pushes - wait for the retrace and go with them.", "3:60",
 "Box-level plays recur in future breakdowns consistent with the taught semantics.", ""),
("indicator", "SFP (swing failure pattern): a failed sweep of a high/low signals reversal - always combined with other confluence, never used alone.", "3:61",
 "SFP citations continue to appear only alongside other confluences.",
 "SFP used as a standalone trigger, repeatedly."),
("indicator", "EMAs: he does not use them; choppy/sideways EMAs mean do nothing (he reads the same from the range), and an EMA flattening at a high-probability level precedes a big move.", "3:63 2:27",
 "Continued absence of EMA-based reasoning in his gold analyses.",
 "EMA-driven entries start appearing in his gold method."),
("indicator", "Intermarket reads: DXY at support implies gold down; silver moves first and gold follows; oil is inversely related; gold and BTC mimic each other - checked as context, not traded signals.", "3:76 2:49 2:50",
 "Intermarket citations continue as context (not entries) and the stated relationships hold in cited windows.",
 "He begins trading gold off intermarket signals alone, or the cited relationships repeatedly invert."),
("indicator", "Bullish RSI divergence at an origin-level retest supports the long.", "3:78",
 "Divergence citations recur at retest longs and are bar-verifiable.", ""),
("indicator", "Volume is read from candle bodies (thin candles = no volume) rather than a volume indicator.", "2:44",
 "Thin-candle language continues to stand in for volume analysis.", ""),
("indicator", "Invert-scale technique: flip the chart to apply long-side concepts symmetrically to shorts.", "1:83",
 "The technique recurs in teaching sessions.", ""),
("indicator", "Prescribed self-backtesting: replay the Asia-break strategy using the indicator's old-Asia-sessions display.", "2:58",
 "Homework assignments recur; members report replay results in sessions.", ""),
("weekly_plan", "Morning routine: mark HTF levels first (daily/weekly/4h/1h), then Asia high/low and the range; identify which level made the extremes plus unmitigated OBs; define the day's buy/sell zones; set alarms and wait for price to come to a zone.", "3:3 2:10 1:11 3:6",
 "Daily posts/streams continue to show pre-marked zones existing before entries (timestamp-verifiable; H-FPL-06 measures the plan-vs-campaign relation).",
 "Entries repeatedly precede any marked plan for the day."),
("weekly_plan", "Two-scenario planning: define scenario long (break high, retest, long) and scenario short (lose low, retest, sell) in advance - including a plan-B zone if the first never taps - and wait for one to confirm.", "1:23 1:79 2:81 2:99",
 "Weekly plans continue to state both scenarios (observed in the W30 Sunday plan).",
 "Plans collapse to single-scenario predictions without alternatives."),
("weekly_plan", "Weekly temporal patterns: Monday+Tuesday set the week's high/low range; after 3+ consecutive down days expect a bounce (~55%); Friday tends to mirror/reverse the week.", "3:0 1:30",
 "The stated patterns hold in bar data over coming weeks at better than chance (descriptive tally only, no fitting).",
 "The patterns fail over a meaningful sample of weeks."),
("weekly_plan", "Demonstrated weekly-plan instances (concrete level ladders; all price digits garble-prone and audio-critical) - retained as provenance for reconstructing plan regions, not as timeless rules.", "1:38 1:58 1:60 2:52 2:53 2:55 3:85 3:86 2:98", "", ""),
("tooling", "Execution tooling: MetaTrader/VT market orders with manual fixed-fraction partial closes at TP zones (or automation); phone alarms on levels replace screen-watching.", "3:93",
 "Future execution descriptions stay consistent (broker/tooling stability).", ""),
("tooling", "Exocharts footprint suite (Fishel education, crypto): chart/tick-size setup, saved templates, delta/CVD + divergence dots, OI and net-positions full-data views, bid/ask footprint support heuristic, TradingView 4-chart synced layout with TR-main - used WITH your own TA, never standalone.", "3:94 3:96 3:99 3:97 3:98 3:95 3:108", "", ""),
("claim", "Gold session statistics (attributed to 22-year data; figures drift between tellings): Asia-high break ~78-80% continuation (Asia-low ~80-85%); London-break variants 63-83%; all three session highs broken claimed '100%'.", "1:3 1:5 1:29 2:0 2:1 3:14", "", ""),
("claim", "BTC session statistics (8-year data): 60-72% continuation variants.", "1:31", "", ""),
("claim", "Win-rate and results claims: 90+% win rate; 22 wins/2 losses month; 2 losses in 20+; 'never a red week/month'; 140K personal month; the gap/ORB algo backtests 'above 90%'.", "1:42 1:55 2:37 2:100 3:101 3:102 3:103", "", ""),
("claim", "Per-trade pip/dollar outcome claims (1000-pip Monday, 400/630/190-200-pip trades, the 60-cent stop-out story, the missed 1600-pip move, member results).", "1:87 2:38 2:68 3:105", "", ""),
("claim", "Crypto growth claims (17K to ~20.2K in ~10 days; $500 doubled in 3 days; 5K wallet to 10-11K).", "3:100 3:104", "", ""),
("claim", "The gold 'algorithm' changes a little every month and then comes back, requiring periodic adjustment.", "2:64", "", ""),
]

EXPL_RANK = {"TAUGHT": 3, "DEMONSTRATED": 2, "PASSING": 1}
used = {}
merges, canon = [], []
for gi, (cat, stmt, mem_s, confirm, kill) in enumerate(G, 1):
    rid = f"FR-{gi:03d}"
    members = []
    for tok in mem_s.split():
        m, i = tok.split(":")
        i = int(i)
        if (m, i) in used:
            raise SystemExit(f"DUPLICATE member {tok} in {rid} (already in {used[(m, i)]})")
        used[(m, i)] = rid
        members.append((m, i, raw[m][i]))
    srcs = [{"file": FILES[m], "index": i, "source_file": e["source_file"],
             "timestamps": e.get("timestamps", [])} for m, i, e in members]
    scopes = {e.get("instrument_scope", "general") for _, _, e in members}
    scope = "crypto" if scopes <= {"crypto"} else ("XAUUSD" if "XAUUSD" in scopes else "general")
    avr = any(e.get("audio_verification_required") for _, _, e in members)
    avr_reasons = " | ".join(dict.fromkeys(
        e.get("avr_reason", "") for _, _, e in members if e.get("avr_reason")))
    expl = max((e.get("explicitness", "PASSING").split()[0] for _, _, e in members),
               key=lambda x: EXPL_RANK.get(x, 0))
    tfiles = {e["source_file"] for _, _, e in members}
    only_ambig = all(e["source_file"] == "fp-10_min_stream.txt" for _, _, e in members)
    some_ambig = any(e["source_file"] == "fp-10_min_stream.txt" for _, _, e in members)
    row = {"rule_id": rid, "statement": stmt, "category": cat, "sources": srcs,
           "source_tier": "PERSONAL_LIVE_METHOD_UNCONFIRMED" + (" TIER_AMBIGUOUS" if only_ambig else ""),
           "instrument_scope": scope, "audio_verification_required": avr, "avr_reason": avr_reasons,
           "explicitness": expl, "repetition_strength": len(tfiles),
           "confirm_condition": confirm, "kill_condition": kill}
    if some_ambig and not only_ambig:
        row["mixed_provenance_note"] = "includes fp-10_min_stream sources (tier-ambiguous) alongside unambiguous ones"
    canon.append(row)
    merges.append({"canonical_rule_id": rid,
                   "merged_from": [{"file": FILES[m], "index": i} for m, i, _ in members],
                   "merge_reason": stmt[:110]})

missing = [f"{m}:{i} {raw[m][i]['statement'][:70]}"
           for m in raw for i in range(len(raw[m])) if (m, i) not in used]
if missing:
    print("MISSING ENTRIES:")
    for x in missing:
        print(" ", x)
    raise SystemExit(1)

json.dump({"method": "human-authored merge of duplicates and phrasing variants across the three miners "
                     "BEFORE novelty gating (reviewer directive 2026-07-21)",
           "raw_entry_counts": {FILES[m]: len(raw[m]) for m in raw}, "merges": merges},
          open(os.path.join(HERE, "dedup_merge_map_v0_1.json"), "w", encoding="utf-8"),
          indent=1, ensure_ascii=False)
json.dump(canon, open(os.path.join(HERE, "canonical_rules_draft_v0_1.json"), "w", encoding="utf-8"),
          indent=1, ensure_ascii=False)
cats = Counter(r["category"] for r in canon)
print(f"raw in: {sum(len(v) for v in raw.values())} | merge groups out: {len(merges)} | canonical: {len(canon)}")
print("by category:", dict(sorted(cats.items())))
print("avr-flagged (G1 pending):", sum(1 for r in canon if r["audio_verification_required"]))
print("crypto-scoped:", sum(1 for r in canon if r["instrument_scope"] == "crypto"))
print("empty-kill (builder will force OBSERVATION):", sum(1 for r in canon if not r["kill_condition"].strip()))
print("single-member groups:", sum(1 for r in canon if len(r["sources"]) == 1))
