"""Shared constants for the paper loop (imported by all modules to avoid __init__ import quirks)."""
SCHEMA_VERSION = "unified-signal-v0.1"
LOOP_VERSION = "paper-loop-v0.1"

PROVIDERS = ("FAROUK", "RUPES", "JOSH_NAVIGATOR", "OTHER")
SOURCE_TYPES = ("TEXT", "IMAGE_CONFIRMED")
DIRECTIONS = ("BUY", "SELL")

PAPER_STATUSES = ("PAPER_READY", "PAPER_OUTSIDE_ZONE", "PAPER_UNKNOWN", "NEEDS_REVIEW")
LABELS = ("OBSERVATION_ONLY", "PAPER_ONLY", "NOT_A_FILL", "NOT_AN_OUTCOME")

PAPER_UNKNOWN_REASONS = ("NO_COVERAGE", "NO_FRESH_QUOTE", "MISSING_BID", "MISSING_ASK",
                         "STALE_BID", "STALE_ASK", "THRESHOLD_CONFIG_MISSING",
                         "SESSION_INTEGRITY_FAILURE", "PARSE_TIME_MISSING")
NEEDS_REVIEW_REASONS = ("AMBIGUOUS_DIRECTION", "ENTRY_RANGE_MISSING", "ENTRY_RANGE_INVALID",
                        "CLOCK_ANOMALY", "UNSUPPORTED_ASSET", "NOT_HUMAN_CONFIRMED",
                        "INVALID_STOP_GEOMETRY", "UNCERTAIN_PROVIDER", "MISSING_EVIDENCE",
                        "MISSING_LISTENER_RECEIVED_AT", "MISSING_PARSED_AT", "UNKNOWN_SOURCE_TYPE")
CONFIRM_DECISIONS = ("CONFIRM", "CORRECT", "REJECT", "NEEDS_MORE_EVIDENCE")
